import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { extname, join, normalize } from 'node:path';
import { setTimeout as sleep } from 'node:timers/promises';
const ROOT='/mnt/IVSTINIANVS/ToyosatomiminoMiko.github.io', DIST=join(ROOT,'dist');
const PORT=8808, CDP_PORT=9728, PROFILE=join(tmpdir(),'shot-pf-profile');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.wasm':'application/wasm','.png':'image/png','.gif':'image/gif','.ico':'image/x-icon','.svg':'image/svg+xml','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf'};
const srv=createServer(async(req,res)=>{try{const url=new URL(req.url,`http://127.0.0.1:${PORT}`);const rel=normalize(decodeURIComponent(url.pathname)).replace(/^(\.\.[/\\])+/,'');const file=join(DIST,rel==='/'?'index.html':rel);if(!file.startsWith(DIST)){res.writeHead(403).end('forbidden');return;}const body=await readFile(file);res.writeHead(200,{'content-type':MIME[extname(file)]??'application/octet-stream'});res.end(body);}catch{if(!res.headersSent){try{res.writeHead(404).end('not found');}catch{}}}});
await new Promise(r=>srv.listen(PORT,'127.0.0.1',r));
rmSync(PROFILE,{recursive:true,force:true});
const chrome=spawn('chromium-browser',['--headless=new',`--remote-debugging-port=${CDP_PORT}`,'--remote-allow-origins=*','--no-sandbox','--disable-gpu','--disable-dev-shm-usage',`--user-data-dir=${PROFILE}`,'--no-first-run','--window-size=1400,620','--force-device-scale-factor=1','about:blank'],{stdio:['ignore','ignore','ignore']});
for(let i=0;i<80;i++){try{await (await fetch(`http://127.0.0.1:${CDP_PORT}/json/version`)).json();break;}catch{await sleep(250);}}
const list=await (await fetch(`http://127.0.0.1:${CDP_PORT}/json/list`)).json();
const page=list.find(t=>t.type==='page');
const ws=new WebSocket(page.webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r));
let id=0;const pending=new Map();
ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}});
const send=(method,params={})=>new Promise(res=>{const i=++id;pending.set(i,res);ws.send(JSON.stringify({id:i,method,params}));});
const ev=async(e)=>{const r=await send('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true});return r.result?.result?.value;};
await send('Page.enable');await send('Runtime.enable');
await send('Page.navigate',{url:`http://127.0.0.1:${PORT}/`});
await sleep(2500);
await ev(`document.querySelector('a[href="#rbt"]').click()`);
await sleep(700);
await ev(`(() => { const i = document.querySelector('#treeInput'); i.value = '10R(5B(3B,7B),40B(2B,50B))'; i.dispatchEvent(new Event('input', { bubbles: true })); })()`);
await sleep(400);
const shot=await send('Page.captureScreenshot',{format:'png'});
await writeFile(join(ROOT,'.tmp_probe','rbt_passfail.png'),Buffer.from(shot.result.data,'base64'));
ws.close();chrome.kill();srv.close();
console.log('saved');
